name: Deploy Rails API

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: rails-health-api-prod
  ECS_CLUSTER: rails-health-api-prod-cluster
  ECS_SERVICE: rails-health-api-prod-service
  TASK_DEFINITION: rails-health-api-prod
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY:${{ env.IMAGE_TAG }} ./app

      - name: Tag Docker image
        run: |
          docker tag $ECR_REPOSITORY:${{ env.IMAGE_TAG }} \
          ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ env.IMAGE_TAG }}

      - name: Push Docker image
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ env.IMAGE_TAG }}

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Get current task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition $TASK_DEFINITION \
            --query taskDefinition > task-def.json

      - name: Prepare new task definition
        run: |
          jq --arg IMAGE "${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ env.IMAGE_TAG }}" \
            '.containerDefinitions[0].image = $IMAGE
            | del(.taskDefinitionArn)
            | del(.revision)
            | del(.status)
            | del(.requiresAttributes)
            | del(.compatibilities)
            | del(.registeredAt)
            | del(.registeredBy)' \
            task-def.json > new-task-def.json

      - name: Register new task definition revision
        id: register-task
        run: |
          TASK_DEF_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://new-task-def.json \
            --query "taskDefinition.taskDefinitionArn" \
            --output text)

          echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV

      - name: Update ECS service to new revision
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE \
            --task-definition $TASK_DEF_ARN

      - name: Wait for deployment to stabilize
        run: |
          aws ecs wait services-stable \
            --cluster $ECS_CLUSTER \
            --services $ECS_SERVICE

      - name: Health Check
        run: |
          curl -f http://rails-health-api-prod-alb-1354214009.us-east-1.elb.amazonaws.com/health
